import {MenuContent} from "../models/content/MenuContent";
import {ContentLabels} from "./ContentLabels";
import {CustomContentTypes} from "../models/content/CustomContentTypes";
import {CircleMenuStates} from "../models/landing/CircleMenuStates";

export enum CommonLabels {
    MENUS = "Menus",
    CONTACT_ME = "Contact Me",
    GIT_HUB = "GitHub",
    THEME = "Theme",
    CLIENT_APPROACH = "Client Approach",
    EXPERIENCE = "Experience",
    PAST_EXPERIENCE = "Past Experience",
    CHESS_DEMO = "Chess Demo",
    CONTACT_PHONE = "(+359) 885 654 188",
    CONTACT_EMAIL = "info@alexander-andreev.com",
    CONTACT_LINKED_IN =  "/in/alexandar-andreev",
    CONTACT_GIT_HUB = "alexander-ra/portfolioWeb",
    CONTACT_RESUME = "Download Resume.pdf",
    LAUNCH_PAGE = "Launch Page",
    HOME = "Home",
    INTRODUCTION = "Introduction",
    MASTERED_SKILLS = "Mastered Skills",
    BY_TITLE = "By Title",
    SENIOR_FRONT_END_DEV = "Front-end Dev",
    OTHER_POSITIONS = "Other Positions",
    BY_FRAMEWORK = "By Framework",
    ANGULAR_JS = "Angular JS/2+",
    REACT_JS = "ReactJS",
    BY_FIELD = "By Field",
    BANKING = "Banking",
    GAMING = "Gaming",
    PAST_CLIENTS = "Past Clients",
    BUSINESS = "Business",
    COMMUNICATION = "Communication",
    SCALING_GROWTH = "Scaling Growth",
    SECURITY = "Security",
    ENCRYPTION = "Encryption",
    QUALITY_ASSURANCE = "Quality assurance",
    SWIFTNESS = "Swiftness",
    SLIM_APPROACH = "Slim approach",
    FAST_LOADING = "Fast Loading",
    COMPATIBILITY = "Compatibility",
    DEVICE_COMPATIBILITY = "Device Support",
    USER_ACCESSIBILITY = "User Accessibility",
    LOADING = "Loading...",
    READY = "Ready!",
    ALEX = "Alex",
    ALEXANDER_ANDREEV = "Alexander Andreev",
    WEB_DEVELOPER = "WEB Developer",
    NEW = "New*",
    PICK_OPPONENT = "Pick Opponent",
    PICK_A_SIDE = "Pick a Side",
    PLAY_CHESS = "Play Chess",
    PLAYER = "Player",
    COMPUTER = "Computer",
    S_TURN = "'s turn",
    WAITING = " waiting",
    CHESS_WIN = "You won! Congratulations!",
    CHESS_DRAW = "It's a draw! Better luck next time!",
    CHESS_LOSE = "You lost! Better luck next time!",
    CHESS_INTERRUPTED = "Game interrupted!",
    PLAY_AGAIN = "Play Again",
    END_GAME = "End Game",
}