export enum LayoutType {
    NATIVE = 'NATIVE',
    MOBILE_LANDSCAPE = 'MOBILE_LANDSCAPE',
    MOBILE_PORTRAIT = 'MOBILE_PORTRAIT',
    TABLET_LANDSCAPE = 'TABLET_LANDSCAPE',
    TABLET_PORTRAIT = 'TABLET_PORTRAIT',
}