export enum LandingDescriptions {
    POSITION_EXPERIENCE_TEXT_LEFT = "I Have been primarily a font-end software developer since 2017. I have mastered the core innerworkings of Javascript/Typescript, DOM Manipulation, Responsive Design and Animations via CSS. I have also completed multiple big projects written using the Angular framework or ReactJS library. More info for that check in [Section3. Framework Experience]. In the part \"Client Approach\" in the website I have written extensifely on some fields of the front end developement that differentiate the ordinary web solution, compared to these that are top of the class.",
    POSITION_EXPERIENCE_TEXT_RIGHT = "Until I have found my love for web developing I have gone trough some different positions that helped me to understand the whole workflow of software developement and shape me as the Proffesional that I am now:\n" +
        "\t- Full-stack developer. Spending hundreds of hours writing back-end software I have a great understanding of the OOP principles, which are much valued in the Front-end world nowadays. Being familliar with Database management, CI/CD, API organisation etc. makes me a great mediator when corrensponding with colleagues from different parts of the team.\n" +
        "\t- Tech Lead - I have led medium sized projects. The work there being much more organisational and managerial than technical I have developed great planning and soft skills.\n" +
        "\t- Technical product analyst: I participated in the complete redesigning of the workflows for an International Bank in one of its countries. Deigning complex workflows as Client onboarding and Mortgage approaval teached me exellent Proffesional Etiquette, Handling information in highly confidential and complex corporate structure and combining expertise from multiple fields to create the best possible outcome for each situation.",
    FIELD_EXPERIENCE_TEXT_LEFT = "- Other than being being a Tech Analyst I have also prepared front end solutions for different banks in the past. From there I gained the knowledge to keep sensitive data secured at all times (See enrypting in client approach). To fully check the quality of the frontend solution using End to End as well as Encapsulated Unit tests. Being the most protected and confidential field with one of the most complex workflows in terms of data management I can easily define and orchestrate heavy processes to be easily usable and understandable by the end user.\n" +
        "\t[Deloitte, Raiffeisen Bank International AG, KBC Group]",
    FIELD_EXPERIENCE_TEXT_RIGHT = "- Gaming in the WEB is quite a difficult task to be executed properly. Having the absolute same experience in term of quality on a vast range of different devices, meanwhile having an unortodox web product is no easy task to achieve. Working with product owners and designers to achieve all of that while keeping user engagement at a high have teached me a lot of ways to make the User Experience pristine. Delivering products for multiple casinos like BetClic, Bet365, William Hill etc. made me pedantic followers of user requirements and international formatting, as the gaming industry is one of the most regulated ones online.",
    FRAMEWORK_EXPERIENCE_TEXT_LEFT = "Initially started working on projects in the initial AngularJS and transitioning to Angular2+ after that. I have exellent understanding of all the inner modules of the framework (Component Livecycles, Angular Directives, RxJS, Angular Animations, Reactive forms, etc..) and have been a Team Lead for projects written in Angular2+. I love angular for the fact that many of the common problems for new project have already been solved in a meaningfull way, so team familiar with it can go straight into developing the business part of the project with relative ease.",
    FRAMEWORK_EXPERIENCE_TEXT_RIGHT = "Around the beggining of 2021 I have decided to move on and try something new by discovering the ReactJS library. Delivering software mostly for real-money handling gaming companies I have a great understanding of how best to handle a lot of dynamic elements for many types of devices using the Virtual DOM, optimising them with The useful React Hooks, while not compromising security of data. I love ReactJS for its ease of use, high responsibility for the user and freedom to really go out of the box and stand out in a unique way in every different project.",
}