export enum CircleMenuStates {
    EXPERIENCE_HOME= "EXPERIENCE_HOME",
    FRAMEWORK= "FRAMEWORK",
    POSITION = "POSITION",
    FIELD= "FIELD",
    APPROACH_HOME= "APPROACH_HOME",
    BUSINESS= "BUSINESS",
    SECURITY = "SECURITY",
    SWIFTNESS = "SWIFTNESS",
    ACCESSIBILITY = "ACCESSIBILITY"
}