export const SET_CHESS_BOARD_PIECES = "SET_CHESS_BOARD_PIECES";
export const RESET_BOARD_STATE = "RESET_BOARD_STATE";
export const SET_SIDE_IN_CHECK = "SET_SIDE_IN_CHECK";
export const SET_EN_PASSANT_SQUARE = "SET_EN_PASSANT_SQUARE";
export const SET_CASTLE_INFO = "SET_CASTLE_INFO";
export const UPDATE_PROCESSED_BOARD = "UPDATE_PROCESSED_BOARD";